const express = require('express')
const router = express.Router()
const {createLogin,createSignin,createBlogPost,getMyPost,getAllPost} = require('../controllers/blog_route_controller')
router.route('/login').post(createLogin)
router.route('/signin').post(createSignin)
router.route('/create').post(createBlogPost)
router.route('/create/:user').get(getMyPost)
router.route('/allpost').get(getAllPost)
// router.route('/register').post(createSignIn).get(getRegisterCred)
// router.route('/create').post(createPost)
// router.route('/seepost').get(getAllPost)
module.exports = router